name: CI

on: pull_request

jobs:
  tests:

    name: Test Python ${{ matrix.python_version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python_version: ['3.7'] # ['3.8', '3.9'] - 3.7 is enough for now, add or upgrade as we like.
    env:
      PYTHONDEVMODE: 1

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python_version }}

    - name: Install dependencies
      run: |
        python -m pip install -U pip
        python -m pip install -r dev-requirements.txt
        python -m pip install -r requirements.txt

    - name: Lint with flake8
      run: |
        python -m flake8

    - name: Lint with mypy
      run: |
        python -m mypy

    - name: Check format with Black
      run: |
        poetry run black --check .

    - name: Test with pytest
      if: false # not ready yet, once we have tests, remove this line.
      run: |
        python -m pytest --cov
      